language: php

# use the new container infrastructure
#sudo: false

php:
  - "5.5"
  - "5.4"
  - "5.3"
  - '7.0'
  - '7.1'

cache:
    directories:
        - vendor

before_script:
  - composer self-update
  - composer update --prefer-source

script:
    - ./bin/phpspec run