language: php
php:
    - "5.4"
    - "5.5"
    - "5.6"
    - "7.0"
    - "hhvm"

# Allow to use container infrastructure
sudo: false

matrix:
    allow_failures:
        - php: "7.0"
        - php: "hhvm"

cache:
  directories:
    - $HOME/.composer/cache

before_script:
    - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    - composer self-update --no-interaction

script:
    - php bin/phpspec run
